CREATE SCHEMA :APP_SCHEMA;
SET search_path TO :APP_SCHEMA, public, pg_catalog;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM PUBLIC;
GRANT ALL PRIVILEGES ON SCHEMA :APP_SCHEMA TO :ADMIN_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA :APP_SCHEMA TO :ADMIN_USER;

\echo created schema :APP_SCHEMA on database :APP_DB_NAME;