CREATE USER :ADMIN_USER WITH ENCRYPTED PASSWORD :ADMIN_PWORD CREATEROLE;
GRANT ALL PRIVILEGES ON DATABASE :APP_DB_NAME TO :ADMIN_USER;

ALTER DEFAULT PRIVILEGES GRANT ALL ON TABLES TO :ADMIN_USER;
ALTER DEFAULT PRIVILEGES GRANT ALL ON SEQUENCES TO :ADMIN_USER;
ALTER DEFAULT PRIVILEGES GRANT ALL ON FUNCTIONS TO :ADMIN_USER;
ALTER DEFAULT PRIVILEGES GRANT ALL ON TYPES TO :ADMIN_USER;
ALTER DEFAULT PRIVILEGES GRANT ALL ON SCHEMAS TO :ADMIN_USER;

\echo created admin user :ADMIN_USER;